# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Minwoo Oh
description: Portfolio page of Minwoo Oh.
baseurl: ""
url: "https://oh-minwoo.github.io/"
og_image: /assets/img/profile_pic.png
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
      slug: /pub
    - name: CV
      slug: https://drive.google.com/file/d/1WSEqU0TBr5O9-tE0tt0y2aDwtUwpjVpz/view?usp=sharing

footer:
  contact:
    - type: email
      icon: fas fa-envelope
      value: "alsdn4435@gm.gist.ac.kr"
    - type: telephone
      icon: fas fa-phone
      value: "+82 10-2321-4435"
    - type: address
      icon: fas fa-map-marker-alt
      value: >
        123 Cheomdangwagi-ro (Oryong-dong), Dasan Building Room 201,<br>
        Buk-gu, Gwangju, Republic of Korea (zip code: 61005)

    


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
